### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by AdrienPeg** [gen-classroom/projet-derder_peguiron_penalva_robertson#65]
Configurez LGTM6 , SonarQube7 ou un outil équivalent pour détecter des bugs et des vulnérabilités dans votre code.
Expliquez en quoi l’un de ces outils vous aura permis d’améliorer vos pratiques de développement

**Comment by RobertsonRhyan** [comment]
Estimated time : 2h

**Comment by RobertsonRhyan** [comment]
Actual Time spent : 1h
