### ISSUE TITLE
Génération du site statique à la volée

### ISSUE THREAD

**Issue by AdrienPeg** [gen-classroom/projet-derder_peguiron_penalva_robertson#69]
En tant qu’utilisateur, j’aimerai que les commandes build et serve puissent régénérer le site statique à la volée, c’està-dire de manière automatique lorsque des changements sont effectués sur le système de fichier. Pour cela, ajoutez
une option --watch aux commandes build et serve et assurez-vous que leur exécution ne se termine pas à la fin du
premier build.
Les générateurs de site statique Jekyll1 et Hugo2 disposent tous deux d’une option --watch. La WatchService API3 de
la librairie standard Java permet d’écouter les changements effectués sur le système de fichiers.
Question ouverte : Faut-il recompiler tous les fichiers lors de chaque changement ?

- [x]  Ajouter --watch à build
- [x]  Ajouter --watch à serve

**Comment by CarlP97** [comment]
Estimated time : 5h
